version: '3'

services:
  weather-api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    volumes:
        - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=peddy
      - POSTGRES_PASSWORD=peddy
      - POSTGRES_DB=weather_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
volumes:
    db_data: